import { ChatGroup, ChatMessage, User } from "./ChatTypes";

export const MOCK_USERS: User[] = [
  { id: "current-user", name: "Me", avatar: "https://ui-avatars.com/api/?name=Me&background=7c2d3e&color=fff", role: "teacher" },
  { id: "user-2", name: "Mr. Wickramasinghe", avatar: "https://ui-avatars.com/api/?name=W&background=3b82f6&color=fff", role: "teacher" },
  { id: "user-3", name: "Mrs. Silva", avatar: "https://ui-avatars.com/api/?name=S&background=10b981&color=fff", role: "parent" },
  { id: "user-4", name: "Amila Perera", avatar: "https://ui-avatars.com/api/?name=A&background=f59e0b&color=fff", role: "student" },
  { id: "admin-1", name: "Principal's Office", avatar: "https://ui-avatars.com/api/?name=P&background=000&color=fff", role: "admin" },
];

export const MOCK_CHATS: ChatGroup[] = [
  {
    id: "group-1",
    name: "Nexis College - Class 10A",
    description: "Official coordination group for Grade 10 - Section A. Please check here for all homework and schedules.",
    avatar: "https://ui-avatars.com/api/?name=10A&background=7c2d3e&color=fff",
    membersCount: 32,
    unreadCount: 5,
    type: "group",
    category: "class",
    ownerId: "current-user",
    createdBy: "Mr. Wickramasinghe",
    createdDate: "2023-09-01",
    members: [
      { ...MOCK_USERS[0], isOwner: true, role: "teacher" },
      { ...MOCK_USERS[1], role: "teacher" },
      { ...MOCK_USERS[2], role: "parent" },
      { ...MOCK_USERS[3], role: "student" },
    ],
    lastMessage: {
      id: "msg-101",
      senderId: "user-2",
      senderName: "Mr. Wickramasinghe",
      type: "text",
      content: "Please check the attached PDF for the math homework.",
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      status: "delivered",
    },
  },
  {
    id: "group-2",
    name: "School Announcements",
    description: "Direct alerts from the school administration. This group is for announcements only.",
    avatar: "https://ui-avatars.com/api/?name=SA&background=f59e0b&color=fff",
    membersCount: 1200,
    unreadCount: 0,
    type: "system",
    category: "all",
    ownerId: "admin-1",
    settings: {
      isAnnouncementOnly: true,
      isMediaSharingDisabled: false
    },
    lastMessage: {
      id: "msg-102",
      senderId: "system",
      senderName: "School Admin",
      type: "text",
      content: "The sports meet has been rescheduled to next Friday.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      status: "read",
    },
  },
  {
    id: "group-3",
    name: "Teacher-Parent Meeting",
    avatar: "https://ui-avatars.com/api/?name=TPM&background=3b82f6&color=fff",
    membersCount: 45,
    unreadCount: 12,
    type: "group",
    category: "management",
    ownerId: "user-2",
    lastMessage: {
      id: "msg-103",
      senderId: "user-3",
      senderName: "Mrs. Silva",
      type: "image",
      content: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      status: "delivered",
    },
  },
];

export const MOCK_MESSAGES: Record<string, ChatMessage[]> = {
  "group-1": [
    {
      id: "msg-1",
      senderId: "user-2",
      senderName: "Mr. Wickramasinghe",
      type: "text",
      content: "Good morning class! Hope you all started the math problems.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
    },
    {
      id: "msg-2",
      senderId: "current-user",
      senderName: "Me",
      type: "text",
      content: "Good morning sir. Yes, I'm working on Chapter 5.",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24.5).toISOString(),
      status: "read",
    },
    {
      id: "msg-3",
      senderId: "user-2",
      senderName: "Mr. Wickramasinghe",
      type: "pdf",
      content: "file_uri_here",
      fileName: "Chapter_5_Notes.pdf",
      fileSize: "2.4 MB",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
      id: "msg-4",
      senderId: "user-4",
      senderName: "Amila Perera",
      type: "text",
      content: "Sir, will this be in the term test?",
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    {
      id: "m1",
      senderId: "u2",
      senderName: "Sarah Johnson",
      type: "text",
      content: "Welcome to Class 10A! Please check the syllabus pinned above.",
      timestamp: "2024-05-20T09:00:00Z",
      status: "read",
      isPinned: true,
    },
    {
      id: "msg-5",
      senderId: "user-2",
      senderName: "Mr. Wickramasinghe",
      type: "text",
      content: "Please check the attached PDF for the math homework.",
      timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    },
  ],
};
